import type { Metadata } from "next";
import localFont from "next/font/local";
import "react-toastify/dist/ReactToastify.css";

import "./globals.css";
import "../../node_modules/boxicons/css/boxicons.min.css";
import Nabar from "./components/NabBar";

const DroidSans = localFont({
  src: "./fonts/DroidSans.ttf",
  variable: "--font-droid-sans",
  weight: "100 400",
});

const DroidSansBold = localFont({
  src: "./fonts/DroidSans-Bold.ttf",
  variable: "--font-droid-sans-bold",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${DroidSans.variable} ${DroidSansBold.variable} antialiased`}
      >
        <Nabar />
        {children}
      </body>
    </html>
  );
}
